---
- name: create a root directory
  file: path="{{ mezzanine_root_path }}" state=directory
  
- name: create a root_project directory
  file: path="{{ mezzanine_root_proj_path }}" state=directory
  
- name: create a static directory
  file: path="{{ mezzanine_static_path }}" state=directory
  
- name: create a logs directory
  file: path="{{ mezzanine_logs_path }}" state=directory
  
- name: create a dump directory
  file: path="{{ mezzanine_dump_path }}" state=directory  
  
- name: check out the repository on the host
  git: 
    repo={{ mezzanine_repo_url }} dest={{ mezzanine_root_proj_path }} accept_hostkey=yes

- name: install pip
  apt: 
    name: python3-pip
    update_cache: yes 
    cache_valid_time: 3600
  become: True

- name: install Python requirements globally via pip
  pip: 
    name: 
      - pip
      - virtualenv
      - virtualenvwrapper
    state: latest
  become: True
  
- name: install required python packages
  pip: 
    name: 
      - gunicorn
      - setproctitle
      - psycopg2-binary
      - django-compressor
      - python-memcached
    virtualenv: "{{ mezzanine_venv_path }}"
    
- name: install requirements.txt
  pip: >
    requirements={{ mezzanine_proj_path }}/{{ mezzanine_reqs_path }}
    virtualenv={{ mezzanine_venv_path }}
    
- name: generate the settings file
  template: src=local_settings.py.j2 dest={{ mezzanine_settings_path }}/local_settings.py
  
- name: apply migrations to create the database
  django_manage:
    command: migrate
    app_path: "{{ mezzanine_proj_path }}"
    virtualenv: "{{ mezzanine_venv_path }}"

- name: apply collect static content
  django_manage:
    command: collectstatic
    app_path: "{{ mezzanine_proj_path }}"
    virtualenv: "{{ mezzanine_venv_path }}"

- name: set the site id
  script: scripts/setsite.py
  environment:
    PATH: "{{ mezzanine_venv_path }}/bin"
    PROJECT_DIR: "{{ mezzanine_proj_path }}"
    PROJECT_APP: "{{ mezzanine_proj_app }}"
    WEBSITE_DOMAIN: "{{ live_hostname }}"
    
- name: set the admin password
  script: scripts/setadmin.py
  environment:
    PATH: "{{ mezzanine_venv_path }}/bin"
    PROJECT_DIR: "{{ mezzanine_proj_path }}"
    PROJECT_APP: "{{ mezzanine_proj_app }}"
    ADMIN_PASSWORD: "{{ admin_pass }}"
    
- name: set the gunicorn config file
  template: src=gunicorn.conf.py.j2 dest={{ mezzanine_proj_path }}/gunicorn.conf.py
  
- name: set the supervisor config file
  template: src=supervisor.conf.j2 dest=/etc/supervisor/conf.d/mezzanine.conf
  become: True
  notify: restart supervisor
  
- name: ensure nginx config path exists
  file: path={{ mezzanine_conf_path }} state=directory
  become: True
  when: tls_enabled
  
- name: restart supervisor
  supervisorctl: name=gunicorn_mezzanine state=restarted
  become: True
  tags: test
  
#- name: create database dump cron job
#  cron: 
#    name="set task to daily database dump" 
#    special_time="daily"
# job="su - postgres && pg_dump {{ database_name }} > {{mezzanine_dump_path}}/`date +%F_%H%M%S`"
