---
# tasks file for roles/mezzanine
- name: install apt packages
  apt: 
    pkg: 
      - git
      - libjpeg-dev
      - libpq-dev
      - memcached
      - nginx
      - python-dev
      - python-pip
      - python-psycopg2
      - python-setuptools
      - python-virtualenv
      - supervisor
    update_cache: yes 
    cache_valid_time: 3600
  become: True
    
- include: django.yml
- include: nginx.yml
